title: >-
  2bcharset%25253Dutf-8%252522%25253E%252bsCu21dd9ROzYL0F68Yg8jl37D21c_0MnmxZ-ouZ1ieo%252b%25253Ctitle
description: >-
  2bcharset%25253Dutf-8%252522%25253E%252bsCu21dd9ROzYL0F68Yg8jl37D21c_0MnmxZ-ouZ1ieo%252b%25253Ctitle%25253EVpn%252bService%252bProviders%252b%25257C%252bVi%2526form%253dANSPH1%2526refig%253dc1e609db94ef435b9c2134cfbb2ce3a9%2526pc%253dU531%2526sp%253d-1%25
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
